BSQ: main.o ft_putstr.o ft_readmap.o ft_square.o ft_strlen.o ft_strncpy.o ft_find_size.o ft_checker.o ft_compare.o ft_disp_square.o ft_translate.o ft_rows.o ft_map_check.o ft_error.o ft_check_info.o ft_find_ret.o ft_assign_globals.o
	gcc main.o ft_checker.o ft_putstr.o ft_readmap.o ft_square.o ft_strlen.o ft_strncpy.o ft_find_size.o ft_compare.o ft_disp_square.o ft_translate.o ft_rows.o ft_map_check.o ft_error.o ft_check_info.o ft_assign_globals.o ft_find_ret.o -o BSQ
main.o: main.c
	gcc -c -Wall -Wextra -Werror main.c
ft_putstr.o: ft_putstr.c
	gcc -c -Wall -Wextra -Werror ft_putstr.c
ft_readmap.o: ft_readmap.c
	gcc -c -Wall -Wextra -Werror ft_readmap.c
ft_square.o: ft_square.c
	gcc -c -Wall -Wextra -Werror ft_square.c
ft_strlen.o: ft_strlen.c
	gcc -c -Wall -Wextra -Werror ft_strlen.c
ft_strncpy.o: ft_strncpy.c
	gcc -c -Wall -Wextra -Werror ft_strncpy.c
ft_find_size.o: ft_find_size.c
	gcc -c -Wall -Wextra -Werror ft_find_size.c
ft_checker.o: ft_checker.c
	gcc -c -Wall -Wextra -Werror ft_checker.c
ft_compare.o: ft_compare.c
	gcc -c -Wall -Wextra -Werror ft_compare.c
ft_translate.o: ft_translate.c
	gcc -c -Wall -Wextra -Werror ft_translate.c
ft_disp_square.o: ft_disp_square.c
	gcc -c -Wall -Wextra -Werror ft_disp_square.c
ft_rows.o: ft_rows.c
	gcc -c -Wall -Wextra -Werror ft_rows.c
ft_map_check.o: ft_map_check.c
	gcc -c -Wall -Wextra -Werror ft_map_check.c
ft_error.o:	ft_error.c
	gcc -c -Wall -Wextra -Werror ft_error.c
ft_check_info.o: ft_check_info.c
	gcc -c -Wall -Wextra -Werror ft_check_info.c
ft_find_ret.o: ft_find_ret.c
	gcc -c -Wall -Wextra -Werror ft_find_ret.c
ft_assign_globals.o: ft_assign_globals.c
	gcc -c -Wall -Wextra -Werror ft_assign_globals.c
clean:
	rm -f *.o
fclean: clean
	rm -f BSQ
