rush-02: main.o ft_putstr.o ft_strlen.o ft_create_inputarray.o ft_search.o ft_translate.o ft_translate_thousand.o ft_decide.o  ft_translate_m.o  ft_translate_b.o ft_translate_t.o ft_translate_quad.o ft_translate_sept.o ft_translate_sex.o ft_translate_qint.o
	gcc -o rush-02 main.o ft_putstr.o ft_strlen.o ft_create_inputarray.o ft_search.o ft_translate.o ft_translate_thousand.o ft_decide.o ft_translate_m.o  ft_translate_b.o ft_translate_t.o ft_translate_quad.o ft_translate_qint.o ft_translate_sept.o ft_translate_sex.o


ft_putstr.o: ft_putstr.c
	gcc -c -Wall -Werror -Wextra ft_putstr.c

ft_strlen.o: ft_strlen.c
	gcc -c -Wall -Werror -Wextra ft_strlen.c

ft_create_inputarray.o: ft_create_inputarray.c
	gcc -c -Wall -Werror -Wextra ft_create_inputarray.c

ft_search.o: ft_search.c
	gcc -c -Wall -Werror -Wextra ft_search.c

ft_translate.o: ft_translate.c
	gcc -c -Wall -Werror -Wextra ft_translate.c

ft_translate_thousand.o: ft_translate_thousand.c
	gcc -c -Wall -Werror -Wextra ft_translate_thousand.c

ft_decide.o: ft_decide.c
	gcc -c -Wall -Werror -Wextra ft_decide.c

ft_translate_m.o: ft_translate_m.c
	gcc -c -Wall -Werror -Wextra ft_translate_m.c

ft_translate_b.o: ft_translate_b.c
	gcc -c -Wall -Werror -Wextra ft_translate_b.c

ft_translate_t.o: ft_translate_t.c
	gcc -c -Wall -Werror -Wextra ft_translate_t.c

ft_translate_quad.o: ft_translate_quad.c
	gcc -c -Wall -Werror -Wextra ft_translate_quad.c

ft_translate_qint.o: ft_translate_qint.c
	gcc -c -Wall -Werror -Wextra ft_translate_qint.c

ft_translate_sex.o: ft_translate_sex.c
	gcc -c -Wall -Werror -Wextra ft_translate_sex.c

ft_translate_sept.o: ft_translate_sept.c
	gcc -c -Wall -Werror -Wextra ft_translate_sept.c

.PHONY: clean fclean

clean: 
	rm *.o

fclean: clean
	rm rush-02
